server:
  port: 8084

spring:
  application:
    name: meetups-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/meetups_db
    username: meetup
    password: meetup
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

clients:
  friends-base-url: ${FRIENDS_BASE_URL:http://localhost:8083}
