server:
  port: 8083

spring:
  application:
    name: friends-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/friends_db
    username: meetup
    password: meetup
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
